# Generated by Django 5.2.11 on 2026-02-08 13:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='settings.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='enrollments.enrollment')),
                ('last_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for_course_progress', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_progress',
                'indexes': [models.Index(fields=['branch', 'status'], name='course_prog_branch__9ece08_idx'), models.Index(fields=['course', 'status'], name='course_prog_course__7b804c_idx'), models.Index(fields=['user', 'status'], name='course_prog_user_id_7af724_idx'), models.Index(fields=['progress_percent'], name='course_prog_progres_fd3dee_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='uniq_user_course_progress')],
            },
        ),
        migrations.CreateModel(
            name='DailyLearningTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='settings.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_learning_time', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_learning_time', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_learning_time',
                'indexes': [models.Index(fields=['date'], name='daily_learn_date_745069_idx'), models.Index(fields=['user', 'date'], name='daily_learn_user_id_1e63bb_idx'), models.Index(fields=['course', 'date'], name='daily_learn_course__e85d9f_idx'), models.Index(fields=['branch', 'date'], name='daily_learn_branch__6802b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course', 'date'), name='uniq_user_course_date')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_position_seconds', models.PositiveIntegerField(default=0)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('last_scroll_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_note', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='settings.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_progress_completed_by', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress_records', to='courses.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_progress_records', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_progress',
                'indexes': [models.Index(fields=['branch', 'status'], name='lesson_prog_branch__79444f_idx'), models.Index(fields=['course', 'status'], name='lesson_prog_course__48b29e_idx'), models.Index(fields=['lesson', 'status'], name='lesson_prog_lesson__4ce257_idx'), models.Index(fields=['user', 'status'], name='lesson_prog_user_id_f63390_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson_progress')],
            },
        ),
        migrations.CreateModel(
            name='ProgressEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('lesson_started', 'Lesson started'), ('lesson_ping', 'Lesson ping'), ('lesson_completed', 'Lesson completed'), ('course_completed', 'Course completed')], db_index=True, max_length=30)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API')], default='web', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='settings.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_events', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_events',
                'indexes': [models.Index(fields=['user', 'created'], name='progress_ev_user_id_984ca3_idx'), models.Index(fields=['course', 'created'], name='progress_ev_course__6387cd_idx'), models.Index(fields=['event_type', 'created'], name='progress_ev_event_t_d3de06_idx')],
            },
        ),
    ]
