# Generated by Django 5.2.11 on 2026-02-08 13:07

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('source', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('medium', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('campaign', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('content', models.CharField(blank=True, max_length=120, null=True)),
                ('term', models.CharField(blank=True, max_length=120, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user_add', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acquisition_campaigns',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=10)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], db_index=True, default='other', max_length=10)),
                ('device_os', models.CharField(blank=True, max_length=60, null=True)),
                ('browser', models.CharField(blank=True, max_length=60, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('landing_path', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('utm_medium', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=120, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=120, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='settings.branch')),
                ('campaign_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='analytics.acquisitioncampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_sessions',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('click', 'Click'), ('search', 'Search'), ('login', 'Login'), ('logout', 'Logout'), ('course_view', 'Course viewed'), ('add_to_cart', 'Added to cart'), ('checkout_started', 'Checkout started'), ('payment_initiated', 'Payment initiated'), ('payment_success', 'Payment success'), ('payment_failed', 'Payment failed'), ('enrolled', 'Enrolled'), ('module_view', 'Module viewed'), ('lesson_start', 'Lesson started'), ('lesson_progress', 'Lesson progress ping'), ('lesson_complete', 'Lesson completed'), ('quiz_start', 'Quiz started'), ('quiz_submit', 'Quiz submitted'), ('quiz_pass', 'Quiz passed'), ('quiz_fail', 'Quiz failed'), ('assignment_submit', 'Assignment submitted'), ('assignment_graded', 'Assignment graded'), ('review_created', 'Review created'), ('cert_issued', 'Certificate issued')], db_index=True, max_length=40)),
                ('name', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('path', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='settings.branch')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='courses.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='content.lesson')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='billing.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.analyticssession')),
            ],
            options={
                'db_table': 'analytics_events',
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('metric', models.CharField(choices=[('active_users', 'Active Users'), ('new_users', 'New Users'), ('sessions', 'Sessions'), ('page_views', 'Page Views'), ('course_views', 'Course Views'), ('checkouts', 'Checkouts Started'), ('orders_paid', 'Orders Paid'), ('revenue', 'Revenue'), ('lesson_starts', 'Lesson Starts'), ('lesson_completions', 'Lesson Completions'), ('watch_time_seconds', 'Watch Time (Seconds)')], db_index=True, max_length=40)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch', to='settings.branch')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_metrics', to='analytics.acquisitioncampaign')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_metrics', to='courses.course')),
            ],
            options={
                'db_table': 'daily_metrics',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAcquisitionCampaign',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('source', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('medium', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('campaign', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('content', models.CharField(blank=True, max_length=120, null=True)),
                ('term', models.CharField(blank=True, max_length=120, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical acquisition campaign',
                'verbose_name_plural': 'historical acquisition campaigns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRetentionCohort',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('cohort_type', models.CharField(choices=[('signup', 'Signup cohort'), ('enrollment', 'Enrollment cohort')], db_index=True, default='signup', max_length=20)),
                ('cohort_date', models.DateField(db_index=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('retention', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='settings.branch')),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.course')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical retention cohort',
                'verbose_name_plural': 'historical retention cohorts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RetentionCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('cohort_type', models.CharField(choices=[('signup', 'Signup cohort'), ('enrollment', 'Enrollment cohort')], db_index=True, default='signup', max_length=20)),
                ('cohort_date', models.DateField(db_index=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('retention', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_cohorts', to='settings.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_cohorts', to='courses.course')),
                ('user_add', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', related_query_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retention_cohorts',
            },
        ),
        migrations.AddIndex(
            model_name='acquisitioncampaign',
            index=models.Index(fields=['source', 'medium'], name='acquisition_source_6feee9_idx'),
        ),
        migrations.AddIndex(
            model_name='acquisitioncampaign',
            index=models.Index(fields=['campaign'], name='acquisition_campaig_d5a898_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['branch', 'started_at'], name='analytics_s_branch__0f15cb_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['user', 'started_at'], name='analytics_s_user_id_89d06e_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['status', 'last_seen_at'], name='analytics_s_status_c46fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['branch', 'occurred_at'], name='analytics_e_branch__ae0246_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='analytics_e_event_t_7b4dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'occurred_at'], name='analytics_e_user_id_d1afb9_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['course', 'occurred_at'], name='analytics_e_course__1ad8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['lesson', 'occurred_at'], name='analytics_e_lesson__a09ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['path', 'occurred_at'], name='analytics_e_path_0de0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['branch', 'date'], name='daily_metri_branch__42e22b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['metric', 'date'], name='daily_metri_metric_e4aeed_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['course', 'date'], name='daily_metri_course__98ee10_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailymetric',
            constraint=models.UniqueConstraint(fields=('branch', 'date', 'metric', 'course', 'campaign'), name='uniq_daily_metric_branch_date_metric_dims'),
        ),
        migrations.AddIndex(
            model_name='retentioncohort',
            index=models.Index(fields=['branch', 'cohort_date'], name='retention_c_branch__917018_idx'),
        ),
        migrations.AddIndex(
            model_name='retentioncohort',
            index=models.Index(fields=['cohort_type', 'cohort_date'], name='retention_c_cohort__c473b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='retentioncohort',
            constraint=models.UniqueConstraint(fields=('branch', 'cohort_type', 'cohort_date', 'course'), name='uniq_retention_cohort_dims'),
        ),
    ]
